### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by 99Kies**
We should download the **pip** dependency before creating the folder.

----
Whether to consider using gunicorn as the startup command?

### CODE REVIEW

**Comment by lewismc** [comment]
+1 for this... any other comments folks? 

Thank you @99Kies

**Comment by 99Kies** [comment]
> +1 for this... any other comments folks?
> 
> Thank you @99Kies

It is finished. If there is anything to be updated later, I will submit another pr/issue.

**Comment by 99Kies** [comment]
> +1 for this... any other comments folks?
> 
> Thank you @99Kies

It was just a cache optimization and a container slimming

**Comment by 99Kies** [comment]
> Suggestions on /incubator-flagon-tap/Dockerfile

I found a **RUN python manage.py runserver 0.0.0.0:8000** in the Dockerfile
It is recommended that you use **ENTRYPOINT** to specify the entry,
It is also possible to start the service through **gunicorn**, not recommended to use the **manager.py** startup service

**Comment by lewismc** [comment]
@99Kies thank you for the contribution.

**Pull request merged**
